//公共
export const COM_LOADING_STATUS = 'COM_LOADING_STATUS'
export const CHAMGE_TITLE = 'CHAMGE_TITLE'


//数据获取 表格
export const RECEIVE_GET_STATION = 'RECEIVE_GET_STATION' //已完成数据获取
export const REQUEST_GET_STATION = 'REQUEST_GET_STATION' //未完成数据获取

export const GET_COMMON_DATA = 'GET_COMMON_DATA'   //新建工单初始值数据

//厂站搜索
export const REQUEST_GET_VALUE_STATION = 'REQUEST_GET_VALUE_STATION'  //厂站搜索呢请求未完成
export const RECEIVE_GET_VALUE_STATION = 'RECEIVE_GET_VALUE_STATION'  //厂站请求完成

//搜索功能 

export const REQUEST_POST_VALUE_SEARCH = 'REQUEST_POST_VALUE_SEARCH' //搜索未完成
export const RECEIVE_POST_VALUE_SEARCH = 'RECEIVE_POST_VALUE_SEARCH' //搜索已完成



//工单详情

export const RECEIVE_GET_VALUE_DETAILS = 'RECEIVE_GET_VALUE_DETAILS'  //工单详情完成
export const REQUEST_GET_VALUE_DETAILS = 'REQUEST_GET_VALUE_DETAILS'  //工单详情未完成




export const GET_CURRENT_LIST = 'GET_CURRENT_LIST' //取数据


export const CHANGE_LOADING = 'CHANGE_LOADING'   //完成提示


export const CHANGE_DEPARTMENT = 'CHANGE_DEPARTMENT' //组织机构


//日志搜索
export const REQUEST_POST_JOURNAL = 'REQUEST_POST_JOURNAL' //日志搜索未完成
export const RECEIVE_POST_JOURNAL = 'RECEIVE_POST_JOURNAL' //日志搜索已完成
export const RECEIVE_POST_JOURNALSELECT = 'RECEIVE_POST_JOURNALSELECT'
export const REQUEST_POST_JOURNALSELECT = 'REQUEST_POST_JOURNALSELECT'




//规则
export const REQUEST_POST_RULE = 'REQUEST_POST_RULE' //日志搜索未完成
export const RECEIVE_POST_RULE = 'RECEIVE_POST_RULE' //日志搜索已完成


//人员规则启动时间


export const  REQUEST_POST_PEOEPL = 'REQUEST_POST_PEOEPL'  //人员启动未完成
export const  RECEIVE_POST_PEOEPL = 'RECEIVE_POST_PEOEPL'  //人员启动已完成

export  const REQUEST_POST_ADD = 'REQUEST_POST_ADD'

export const ADD_TODO = 'ADD_TODO'

export const TOGGLE_TODO = 'TOGGLE_TODO'


export const RECEIVE_GET_VALUE_JOUTDTAUI = 'RECEIVE_GET_VALUE_JOUTDTAUI'



export const REQUEST_GET_SG_HIFT = 'REQUEST_GET_SG_HIFT'
export const RETIVE_GET_SG_HIFT = 'RETIVE_GET_SG_HIFT'



//列出所有角色

export const REQUEST_GET_SY_ROLES = 'REQUEST_GET_SY_ROLES'
export const RETIVE_GET_SY_ROLES = 'RETIVE_GET_SY_ROLES'


//列出所有角色
export const GET_PRIVILEGES = 'GET_PRIVILEGES'


//角色详情
export const GET_PRIVILEGES_ROLE = 'GET_PRIVILEGES_ROLE'
export const GET_PRIVILEGES_ROLENAMW = 'GET_PRIVILEGES_ROLENAMW'


//角色分配
export const GET_PRIVILEGES_ROLEUSRALL = 'GET_PRIVILEGES_ROLEUSRALLDATA'
export const GET_PRIVILEGES_ROLEUSRALLNAME = 'GET_PRIVILEGES_ROLEUSRALLNAME'

//所有人员
export const GET_PRIVILEGES_ROLEUSRALL_USER = 'GET_PRIVILEGES_ROLEUSRALL_USER'
//所有权限
export const GEUTALLUSERPERMISSIONS = 'GEUTALLUSERPERMISSIONS'